import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import { AnimationWrapper } from "@/components/shared/animation-wrapper/AnimationWrapper";
import { CoverScreen } from "@/components/shared/cover-screen/CoverScreen";
import { Header } from "@/components/shared/header/Header";
import { OrientationGuide } from "@/components/shared/orientation-guide/OrientationGuide";
import "./globals.css";

const geistMono = Geist_Mono({
	subsets: ["latin"],
	variable: "--font-geist-mono",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const RootLayout = ({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) => {
	return (
		<html lang="ja">
			<head>
				<link rel="manifest" href="/manifest.json" />
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1.0, user-scalable=no"
				/>
			</head>
			<body className={`dark antialiased ${geistMono.variable}`}>
				<OrientationGuide />
				<Header />
				<div className="fixed inset-0 h-screen w-screen bg-gray-900">
					<CoverScreen />
					<AnimationWrapper>{children}</AnimationWrapper>
				</div>
			</body>
		</html>
	);
};

export default RootLayout;
