import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import { Header } from "@/components/shared/header/Header";
import "./globals.css";

const geistMono = Geist_Mono({
	subsets: ["latin"],
	variable: "--font-geist-mono",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const RootLayout = ({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) => {
	return (
		<html lang="ja">
			<body className={`dark antialiased ${geistMono.variable}`}>
				<Header />
				<div className="fixed inset-0 h-screen w-screen bg-gray-900">
					{children}
				</div>
			</body>
		</html>
	);
};

export default RootLayout;
